### ISSUE TITLE
Great introduction in the README, but I want to see more! 

### ISSUE THREAD

**Issue by Jwomers** [fission-codes/fission-codes#25]
I'm a big fan of Fission codes, great work!

When looking at this GitHub repo's root page (README) I'd love to see a quick simple example of using the library to implement FISSION codes, so I can see how easy it is and get an idea of how it all works (a simple JS example and Solidity example) to show the ease and power of FISSION.

**Comment by expede** [comment]
@Jwomers Great suggestion! The README has been hurting for a _while_. I just merged some README updates (#27) to `master`. I would love to hear your thoughts!

**Comment by Jwomers** [comment]
Great improvements! 👍

**Comment by expede** [comment]
Hooray! Thank you!
